### ISSUE TITLE
Docs: Errors in the readme?

### ISSUE THREAD

**Issue by fmmix** [litestar-org/litestar-hello-world-stale#88]
### Summary

Hey,

shouldn't you curl /sync or /async instead of / ? - otherwise you'll get a 404.

For the unicorn proccess, shouldn't the name be  poetry run uvicorn **app**:app --reload

since there is no main?

ERROR:    Error loading ASGI app. Could not import module "main".

Kind regards.

**Comment by peterschutt** [comment]
Thanks, there wasn't always `/sync` and `/async` routes, just a single plain `/` route, and I mustn't have update the readme when I updated the app.

PRs welcome!

**Comment by JacobCoffee** [comment]
This is done in the new version. Thank you!
